# yamllint disable rule:line-length
# SPDX-FileNotice: 🅭🄍1.0 This file is dedicated to the public domain using the CC0 1.0 Universal Public Domain Dedication <https://creativecommons.org/publicdomain/zero/1.0/>.
# SPDX-FileContributor: Jason Yundt <jason@jasonyundt.email> (2021–2023)
# yamllint enable


%YAML 1.2
---
# Rationale: CC0-1.0.txt contains the official plain text version of CC0 [1].
# From a copyright perspective, it’s OK to modify CC0’t text [2]. The caveat is
# that CC0 contains trademarks that are owned by Creative Commons [3]. Creative
# Commons does give us a license to use those trademarks, but that license
# stipulates that you can’t use those trademarks with modified versions of
# Creative Commons legal tools. CC0 is a Creative Commons legal tool [4], so if
# we modify CC0, then we have to remove any Creative Commons trademarks from it.
#
# Excluding CC0-1.0.txt makes sure that pre-commit won’t inadvertently encourage
# someone to modify CC0’s text. In general, legal text should be handled with
# care and not automatically modified by a tool.
#
# I’m also excluding CC0-1.0.txt.spdx-meta since it would be annoying to make
# that file and CC0-1.0.txt pass the assert_contains_regex hook.
#
# yamllint disable rule:line-length
# [1]: <https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F>
# [2]: <https://github.com/creativecommons/creativecommons.org/issues/1218#issuecomment-1212525987>
# [3]: <https://creativecommons.org/policies/#trademark>
# [4]: <https://creativecommons.org/faq/#what-is-creative-commons-and-what-do-you-do>
exclude: "^CC0-1\\.0\\.txt(\\.spdx-meta)?$|^LICENSES\\/.*"
repos:
    -
        repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.3.0
        hooks:
            - id: check-yaml
            - id: check-case-conflict
            - id: check-executables-have-shebangs
            - id: check-merge-conflict
            - id: check-symlinks
            - id: check-vcs-permalinks
            - id: check-shebang-scripts-are-executable
            - id: destroyed-symlinks
            - id: detect-private-key
            - id: end-of-file-fixer
            - id: mixed-line-ending
            - id: trailing-whitespace
    -
        repo: https://github.com/jumanjihouse/pre-commit-hooks
        rev: 2.1.6
        hooks:
            -
                id: forbid-space-in-indent
                # YAML requires spaces for indentation. See:
                # <https://yaml.org/spec/1.2.2/#61-indentation-spaces>
                # Pipfile.lock is automatically generated.
                exclude: '.*\.yaml$|(.*/)?Pipfile\.lock$'
                # This is a workaround the following issue:
                # <https://github.com/jumanjihouse/pre-commit-hooks/issues/69>
                types: ['text']
    -
        repo: https://github.com/adrienverge/yamllint
        rev: v1.26.3
        hooks:
            - id: yamllint
    -
        repo: https://github.com/igorshubovych/markdownlint-cli
        rev: v0.31.1
        hooks:
            - id: markdownlint
    -
        repo: https://pagure.io/assert_contains_regex.git
        rev: 0.0.0
        hooks:
            -
                id: assert_contains_regex
                args:
                    - --companion-suffix
                    - .spdx-meta
                    - --pattern
                    - >
                        SPDX-(FileNotice): 🅭🄍1\.0 This file is dedicated to the
                        public domain using the CC0 1\.0 Universal Public
                        Domain Dedication
                        <https://creativecommons.org/publicdomain/zero/1\.0/>\.
                    - --pattern
                    - >
                        SPDX-FileContributor:
                        .+( <.+>)?
                        \(([0-9]{4}[-–])?[0-9]{4}\)
